import type { Metadata } from "next";
import "../globals.css";
import { kanit, k2d } from "../fonts";
import { Toaster } from "@/components/ui/sonner";
import DLayout from "./dashboard/components/DLayout";

export const metadata: Metadata = {
  title: "Dashboard",

  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${k2d.variable},${kanit.variable}  antialiased`}>
        <DLayout>{children}</DLayout>

        <Toaster richColors />
      </body>
    </html>
  );
}
