import type { Metadata } from "next";
import "./globals.css";
import { kanit, k2d } from "./fonts";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${k2d.variable},${kanit.variable}  antialiased`}>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
