import type { Metadata } from "next";
import "../globals.css";
import { kanit, k2d } from "../fonts";
import AppHeader from "@/components/app/AppHeader";

export const metadata: Metadata = {
  title: "Next.js E-Commerce",
  description: "Generated by create next app",
};

export default function FrontLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${k2d.variable},${kanit.variable}  antialiased`}>
        <AppHeader />
        {children}
      </body>
    </html>
  );
}
